# Generated by Django 4.1.1 on 2022-09-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='public',
        ),
        migrations.AddField(
            model_name='api',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
