# Generated by Django 4.1.1 on 2022-09-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_api_public_api_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='title',
        ),
    ]
