# Generated by Django 4.1.1 on 2022-09-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_api_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
