# Generated by Django 4.1.1 on 2022-10-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_api_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api',
        ),
    ]
