# Generated by Django 4.1.1 on 2022-10-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_api'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api',
            new_name='LyricsApi',
        ),
    ]
