# Generated by Django 4.1.2 on 2022-10-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lyrics_delete_lyricsapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyrics',
            old_name='author',
            new_name='author_id',
        ),
    ]
